### ISSUE TITLE
Mac M1/2/...∞ Woes, Natives Incompatibilities

### ISSUE THREAD

**Issue by sylv256** [babric/polymc-instance#5]
the L in LWJGL stands for always Losing
```
[23:29:54] [Minecraft main thread/ERROR] (FabricLoader) Uncaught exception in thread "Minecraft main thread"
java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path: /Users/sylv/Library/Application Support/PrismLauncher/instances/babric-b1.7.3/natives
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434) ~[?:?]
	at java.lang.Runtime.loadLibrary0(Runtime.java:818) ~[?:?]
	at java.lang.System.loadLibrary(System.java:1989) ~[?:?]
	at org.lwjgl.Sys$1.run(Sys.java:72) ~[lwjgl-2.9.4-babric.1.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66) ~[lwjgl-2.9.4-babric.1.jar:?]
	at org.lwjgl.Sys.loadLibrary(Sys.java:96) ~[lwjgl-2.9.4-babric.1.jar:?]
	at org.lwjgl.Sys.<clinit>(Sys.java:117) ~[lwjgl-2.9.4-babric.1.jar:?]
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135) ~[lwjgl-2.9.4-babric.1.jar:?]
	at net.minecraft.client.Minecraft.method_2106(Minecraft.java:244) ~[client-intermediary.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:716) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
### Status
The issue has been [fixed](https://github.com/babric/prism-instance/issues/5#issuecomment-2383646697) and is awaiting a merge upstream.

**Comment by sylv256** [comment]
When reverting to regular LWJGL, the G and B channels are swapped resulting in a weird-looking game.

**Comment by thecatcore** [comment]
Use this instance instead: https://github.com/telvarost/prism-instance.

**Comment by calmilamsy** [comment]
That instance does not ship with proper M1 natives. I'll sort out a proper instance when I get on (~3-4hrs, bump if I haven't done anything by then)

**Comment by thecatcore** [comment]
Also install this mod: https://modrinth.com/mod/gambac

**Comment by thecatcore** [comment]
> That instance does not ship with proper M1 natives. I'll sort out a proper instance when I get on (~3-4hrs, bump if I haven't done anything by then)

I remember seeing an instance shipping LF LWJGL but I can't find it anymore.

**Comment by calmilamsy** [comment]
I started work on one, then got sidetracked, lmao

**Comment by DanyGames2014** [comment]
> > That instance does not ship with proper M1 natives. I'll sort out a proper instance when I get on (~3-4hrs, bump if I haven't done anything by then)
> 
> I remember seeing an instance shipping LF LWJGL but I can't find it anymore.

Babric Enriched ships with LF LWJGL, maybe thats what you reacall ?

**Comment by thecatcore** [comment]
Oh yeah probably.

**Comment by sylv256** [comment]
> Also install this mod: https://modrinth.com/mod/gambac

I suggest shipping the M1 version with this mod pre-installed.

**Comment by DanyGames2014** [comment]
> > Also install this mod: https://modrinth.com/mod/gambac
> 
> I suggest shipping the M1 version with this mod pre-installed.

Please no :( Im already blamed for 80% of Babric crash logs

**Comment by calmilamsy** [comment]
https://github.com/Glass-Series/babric-prism-instance/releases

Note: You'll still need gambac to solve the G and B channel switching.

**Comment by sylv256** [comment]
The Glass Series prism instance with Gambac crashes https://mclo.gs/ic3GT18

**Comment by sylv256** [comment]
telvarost's prism instance with Gambac also crashes https://mclo.gs/7XNTfEc

**Comment by sylv256** [comment]
It seems to delete the `natives` folder lol.

**Comment by sylv256** [comment]
This is what I get when I use the Glass Series instance without Gambac: https://mclo.gs/YrqNb9D
This is telvarost's instance without Gambac: https://mclo.gs/qsVERRj

**Comment by calmilamsy** [comment]
Try the newest version now. If it doesn't work, I'll dig out the crapbook and take a closer look when I'm next around.

**Comment by sylv256** [comment]
It's giving the same exact error with no `natives` folder in sight https://mclo.gs/XOmEZqm

**Comment by calmilamsy** [comment]
The natives folder is a temporary folder.

**Comment by calmilamsy** [comment]
Sigh. Give me a moment.

**Comment by calmilamsy** [comment]
Okay yeah, just hit edit instance, and changle the lwjgl version to be the normal prism one. For some reason macos natives are just not downloading in the first place, and it's not showing me any logs, which is fucking helpful.

**Comment by sylv256** [comment]
what if it's called `arm64` rather than `aarch64`
that's the naming convention of the newer LWJGL 3 stuff

**Comment by sylv256** [comment]
The normal LWJGL (2.9.4-nightly-whateveridk) works well with Gambac. Unfortunately, SmoothBeta doesn't work because of some silly macOS-specific GLSL syntax nightmare, so that sucks.
One big issue however: the audio does not work at all. https://mclo.gs/eS9vUed

**Comment by sylv256** [comment]
Narrowing it down, it appears it's one of the mods in my list. I'll go bug the offending mods' issue tracker. In the meantime, I'll keep this issue open since this still affects an unmodified prism instance.

**Comment by calmilamsy** [comment]
You have an error related to not having GCAPI2 installed. Install that and see if the audio issues continue, cause I have audio on the crapbook.

**Comment by sylv256** [comment]
Using Glass Config API 2 with MojangFix Station API, there is still no audio. https://mclo.gs/eooMt3N

**Comment by calmilamsy** [comment]
I know what's wrong with the instance, I'll get on it when I get on tomorrow, gotta sleep now though.

**Comment by sylv256** [comment]
After a bit of gaming, the audio came back. 😕

**Comment by calmilamsy** [comment]
Alright, fully fixed on the latest glass-series release of the instance.

> After a bit of gaming, the audio came back. 😕

Makes sense, minecraft was probably still loading all sounds.

**Comment by sylv256** [comment]
Should we make a PR with the fix?
